version: "2"
services:
  redis:
    build:
      context: ./redis
    image: redis
    user: root
    network_mode: "host"
    volumes:
      - /data/stager/db:/data
  irodsclient:
    build:
      context: ./irodsclient
    image: irodsclient
  stager:
    build: ./stager
    image: stager
    network_mode: "host"
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    volumes:
      - /data/stager/config:/opt/stager/config
      - /data/stager/log:/opt/stager/log
      - ./stager/cron:/cron
      - /home:/home:ro
      - /project:/project
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    depends_on:
      - irodsclient
      - redis
  stager-ui:
    build: ./stager-ui
    image: stager-ui
    network_mode: "host"
    volumes:
      - /data/stager-ui/config:/opt/stager-ui/config
    depends_on:
      - stager
