version: "2"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    network_mode: "host"
    volumes:
      - /scratch/data_stager:/data
  irodsclient:
    build:
      context: ./irodsclient
    image: irodsclient
  stager:
    build: ./stager
    image: stager
    network_mode: "host"
    volumes:
      - ./stager/config/default.json:/opt/stager/config/default.json
      - /home:/home:ro
      - /project:/project
      - /var/lib/sss/pipes:/var/lib/sss/pipes
      - /var/lib/sss/mc:/var/lib/sss/mc:ro
    depends_on:
      - irodsclient
      - redis
  stager-ui:
    build: ./stager-ui
    image: stager-ui
    network_mode: "host"
    volumes:
      - ./stager-ui/config/default.json:/opt/stager-ui/config/default.json
    depends_on:
      - stager
