version: "2"

services:

  stager-db:
    build:
      context: ./redis
    image: redis
    hostname: stager-db
    user: root
    volumes:
      - ./data/db:/data
    networks:
      - rdm-network

  irodsclient:
    build:
      context: ./irodsclient
    image: irodsclient

  stager:
    build: ./stager
    image: stager
    hostname: stager
    environment:
      - REDIS_HOST=stager-db
      - REDIS_PORT=6379
      - IRODS_ADMIN_USER=irods
      - IRODS_ADMIN_CREDENTIAL=/opt/stager/config/secret
      - IRODS_ICAT_HOST=irods-icat
      - IRODS_ZONE_PORT=1247
      - IRODS_ZONE_NAME=rdmtst
    volumes:
      - ./stager/config:/opt/stager/config
      - ./stager/config/icat.pem:/opt/irods/ssl/icat.pem:ro
      - ./stager/config/keypair.pem:/opt/stager/ssl/private.pem:ro
      - ./data/log/stager:/opt/stager/log
    networks:
      - rdm-network
    depends_on:
      - irodsclient
      - stager-db

  stager-ui:
    build: ./stager-ui
    image: stager-ui
    environment:
      - DAVRODS_ENDPOINT=https://irods-webdav
      - DAVRODS_EXPOSED_ROOT=/rdmtst/di
    volumes:
      - ./stager-ui/config:/opt/stager-ui/config
      - ./stager-ui/config/irods-webdav.pem:/opt/stager-ui/ssl/irods-webdav.pem:ro
      - ./stager-ui/config/public.pem:/opt/stager-ui/ssl/public.pem:ro
    networks:
      - rdm-network
    ports:
      - 3080:3080
    depends_on:
      - stager

networks:
    rdm-network:
      external: true
