version: "2"

services:
  stager:
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /home:/data
  stager-ui:
    environment:
      - DAVRODS_ENDPOINT=https://webdav.data.donders.ru.nl
      - DAVRODS_EXPOSED_ROOT=/rdm/di
